import { defineConfig } from 'astro/config';

// Change this if you connect a custom domain (recommended for SEO — see README)
const SITE_URL = 'https://visuails-app.pages.dev';

// Note: sitemap is generated by our own src/pages/sitemap.xml.js rather than
// @astrojs/sitemap — that package crashed the build with an internal
// "Cannot read properties of undefined (reading 'reduce')" error (a known
// version-compatibility issue in the package itself, not our code). A
// hand-written endpoint from the same data files is more reliable and gives
// full control over what's included (e.g. excluding noindex pages).
//
// No @astrojs/react integration — every interactive element (style tabs,
// carousels, the process demo) is pure CSS, so there's no client-side
// framework to hydrate anywhere on the site.
export default defineConfig({
  site: SITE_URL,
  output: 'static',
});
